# One Health Global â€” Orderer Service


networks:
  ohg-network:
    name: ohg-network
    external: true

volumes:
  orderer.onehealthglobal.com:

services:
  orderer.onehealthglobal.com:
    image: hyperledger/fabric-orderer:2.5.9
    container_name: orderer.onehealthglobal.com
    hostname: orderer.onehealthglobal.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OHGOrdererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # Genesis via channel participation
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      # Admin service
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # Cluster
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # Metrics
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.onehealthglobal.com:8443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../../organizations/ordererOrganizations/onehealthglobal.com/orderers/orderer.onehealthglobal.com/msp:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/onehealthglobal.com/orderers/orderer.onehealthglobal.com/tls:/var/hyperledger/orderer/tls
      - orderer.onehealthglobal.com:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
      - "7053:7053"
      - "8443:8443"
    networks:
      - ohg-network
